### PR TITLE
Compiler-enforced typesafe ctor for AtomTypes

### PR DESCRIPTION
**Pull request by kanduri**
This is a way to ensure that the compiler forces the user to employ named parameter types. 

It looks very inelegant to me. But the compiler seems to auto-deduce the types in the branch nblib_usingClass-SpeciicDataTypes.

### CODE REVIEW

**Review by ejjordan — CHANGES_REQUESTED** [review]
This is not what was asked for, and is not even a complete implementation of the thing it is. All that is needed is a few using declarations to ensure that the caller is passing parameters in the right order. Please just implement that, as illustrated in PR #7.

**Comment by kanduri** [comment]
I implemented exactly that in #12 and it doesn't achieve the objective we have of making the compiler prevent the implicit conversion. In the case of Atom, the user can still mess up the order between charge, mass, c6, or c12 because they all can be implicitly converted from `real`/`double`/`float`. 

In PR #11, a way has been highlighted to force the user to explicitly say something like: `Atom(..., AtomicMass(42.2), AtomicCharge(-1.2), ...);`

I am using this PR as a way to show and discuss the design whether it achieves the required objectives or not. Just simply setting some data types doesn't force the user to employ the right order. Neither does the compiler put any checks.

**Comment by ejjordan** [comment]
You can just delete the constructor with the implicit types to prevent conversion. I will do this in PR #7  as well.

**Comment by kanduri** [comment]
Constructor for Atom in PR #12 has no arguments of data types like `real` or `std::string`. The constructor only contains aliases defined in the same header.

**Pull request closed without merging**
