### PR TITLE
Nblib rebase on master

### PR DESCRIPTION
**Pull request by ejjordan**

### CODE REVIEW

**Review by kanduri — COMMENTED** [review]
I don't think one can really "review" this PR. If all the NB-LIB UTs pass, then thumbs up it is.

**Comment by ejjordan** [comment]
> I don't think one can really "review" this PR. If all the NB-LIB UTs pass, then thumbs up it is.

There is one implicit design decision in the second commit, which is that I put atomtype.h, molecule.h, and topology.h in the public api documentation. I suspect that we will need to revisit what files go to what documentation level when we are exposing the library headers, so this may not be such a useful discussion to have right now. I just want to make sure to be explicit about that small change, which mostly currently affects how complete include paths in some files need to be for now.

**Review by kanduri — APPROVED** [review]
LGTM.

We really need to get in the GROMACS master fast. Then this rebasing business won't be as intrusive. Hoping for a speedy Gitlab transition.

**Comment by ejjordan** [comment]
> We really need to get in the GROMACS master fast. Then this rebasing business won't be as intrusive. Hoping for a speedy Gitlab transition.

We need to define our own internal acceptance criteria for when we think our code will be ready to go into gromacs master before we can actually ask to get the code in. I will put something on slack.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Pull request merged**
