### PR TITLE
Add copyright and author info to nblib files

### PR DESCRIPTION
**Pull request by ejjordan**

### CODE REVIEW

**Review by kanduri — APPROVED** [review]
Straightforward review. Approved.

**Comment by ejjordan** [comment]
This is actually broken. I will update this change so that the doxygen is correct.

**Review by sekelle — APPROVED** [review]
lgtm

**Comment by ejjordan** [comment]
OK I will merge this then and push up another change that fixes the doxygen so that the check-source target does not produce errors.

**Pull request merged**
